[package]
name = "mullvad-exclude"
version = "2021.3.0-beta1"
authors = ["Mullvad VPN"]
license = "GPL-3.0"
edition = "2018"
publish = false

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.19"
err-derive = "0.3.0"
talpid-types = { path = "../talpid-types" }
