name: Verify lockfile signatures
on:
    pull_request:
        paths:
            - .github/workflows/verify-lockfile-signatures.yml
            - Cargo.lock
            - gui/package-lock.json
    workflow_dispatch:
jobs:
    verify-signatures:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - run: ci/verify-lockfile-signature.sh origin/master
